<!-- Discord -->
<a href="https://discordapp.com/invite/52KpmuH" target="_blank" aria-label="Join our Discord server"><img src="https://img.shields.io/discord/317348946144002050.svg?style=for-the-badge&logo=discord" alt="Discord"></a>
<!-- Github Downloads -->
<a href="https://github.com/sogehige/sogeBot/releases" target="_blank"><img src="https://img.shields.io/github/release/sogehige/sogebot.svg?style=for-the-badge"/></a>
<!-- Github Release -->
<a href="https://github.com/sogehige/sogeBot/releases" target="_blank"><img src="https://img.shields.io/github/downloads/sogehige/sogebot/total.svg?style=for-the-badge"/></a>
<!-- Paypal -->
<a href="https://www.paypal.me/sogetwitch/5eur" target="_blank"><img src="https://img.shields.io/badge/paypal-donate-yellow.svg?style=for-the-badge&logo=paypal"/></a>
<!-- Patreon -->
<a href="https://www.patreon.com/soge" target="_blank"><img src="https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fshieldsio-patreon.herokuapp.com%2Fsoge__&style=for-the-badge"/></a>

